spring:
  config:
    import: file:env.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0

application:
  security:
    jwt:
      secret-key: 4337786E56516674686144666C55626C6C39642B325662564A593037507473437A5957595A526F5042324E372F546551464B536F4F34737650424352455A2B310A
      expiration: 86400000
      refresh-token:
        expiration: 604800000


message:
  post:
    not-found: Could not find post
    not-found-visible: Could not find visible post
  user:
    not-found: Could not find user
  token:
    not-found: Could not find token