spring:
  config:
    import: file:env.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0

message:
  post:
    not-found: Could not find post with given id
    not-found-visible: Could not find visible post with given id